using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class BG_Offer : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Offer(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Offer(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4872613830185334496UL,6941107191703223697UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.Int32 f_Id
	{
		get => _f_Id[Index];
		set => _f_Id[Index] = value;
	}
	public System.String f_ResourceType
	{
		get => _f_ResourceType[Index];
		set => _f_ResourceType[Index] = value;
	}
	public System.String f_Name
	{
		get => _f_Name[Index];
		set => _f_Name[Index] = value;
	}
	public System.Int32 f_Value
	{
		get => _f_Value[Index];
		set => _f_Value[Index] = value;
	}
	public System.Int32 f_Price
	{
		get => _f_Price[Index];
		set => _f_Price[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5073448970793139310UL, 4792745547861918864UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Id;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Id => _ufle12jhs77_f_Id ?? (_ufle12jhs77_f_Id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5736589885563410787UL, 1782991208798290059UL), () => _ufle12jhs77_f_Id = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_ResourceType;
	public static BansheeGz.BGDatabase.BGFieldString _f_ResourceType => _ufle12jhs77_f_ResourceType ?? (_ufle12jhs77_f_ResourceType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5291164480989949533UL, 5981785298287584430UL), () => _ufle12jhs77_f_ResourceType = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Name;
	public static BansheeGz.BGDatabase.BGFieldString _f_Name => _ufle12jhs77_f_Name ?? (_ufle12jhs77_f_Name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5520040995894898455UL, 11191801351269304237UL), () => _ufle12jhs77_f_Name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Value;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Value => _ufle12jhs77_f_Value ?? (_ufle12jhs77_f_Value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5696382303739992291UL, 3419916450576510351UL), () => _ufle12jhs77_f_Value = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Price;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Price => _ufle12jhs77_f_Price ?? (_ufle12jhs77_f_Price = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4796512726208534206UL, 15292070147101593247UL), () => _ufle12jhs77_f_Price = null));
	private static readonly BG_Offer.Factory _factory0_PFS = new BG_Offer.Factory();
	private BG_Offer() : base(MetaDefault) {}
	private BG_Offer(BGId id) : base(MetaDefault, id) {}
	private BG_Offer(BGMetaEntity meta) : base(meta) {}
	private BG_Offer(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_Offer FindEntity(Predicate<BG_Offer> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_Offer> FindEntities(Predicate<BG_Offer> filter, List<BG_Offer> result=null, Comparison<BG_Offer> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_Offer> action, Predicate<BG_Offer> filter=null, Comparison<BG_Offer> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_Offer GetEntity(BGId entityId) => (BG_Offer) MetaDefault.GetEntity(entityId);
	public static BG_Offer GetEntity(int index) => (BG_Offer) MetaDefault[index];
	public static BG_Offer GetEntity(string entityName) => (BG_Offer) MetaDefault.GetEntity(entityName);
	public static BG_Offer NewEntity() => (BG_Offer) MetaDefault.NewEntity();
	public static BG_Offer NewEntity(BGId entityId) => (BG_Offer) MetaDefault.NewEntity(entityId);
	public static BG_Offer NewEntity(Action<BG_Offer> callback) => (BG_Offer) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_Offer)entity)));
}
#pragma warning restore 414
